name = "NewtonRaphson"
uuid = "924084a1-7781-44a2-bd3a-95272aed68ae"
authors = ["Daniel Ribeiro <dwribeirodh@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
LinearAlgebra = "1.11.0"
Revise = "3.7.2"
